import "server-only";

import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import type { Company, OnboardingSubmission } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { publicBgosOrigin, publicIceconnectOrigin } from "@/lib/host-routing";
import type { WorkflowTemplateSections } from "@/lib/onboarding-workflow-types";

export async function generateOnboardingDeliveryPdf(params: {
  submission: OnboardingSubmission;
  company: Pick<Company, "id" | "name">;
  sections: WorkflowTemplateSections;
}): Promise<string> {
  const { submission, company, sections } = params;
  const dir = path.join(process.cwd(), "public", "deliveries");
  fs.mkdirSync(dir, { recursive: true });
  const filename = `${submission.id}.pdf`;
  const filepath = path.join(dir, filename);
  const publicPath = `/deliveries/${filename}`;

  const manuals = await prisma.userManual.findMany({
    where: { companyId: company.id },
    select: { category: true, fileUrl: true },
  });

  const members = await prisma.userCompany.findMany({
    where: { companyId: company.id },
    include: { user: { select: { email: true, name: true, isActive: true } } },
    take: 40,
  });

  const data = (submission.data ?? {}) as Record<string, string>;

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    doc.fontSize(20).text("BGOS — Delivery document", { underline: true });
    doc.moveDown();
    doc.fontSize(11);
    doc.text(`Company: ${company.name}`);
    doc.text(`Plan tier: ${submission.planTier}`);
    doc.text(`Category: ${submission.category}`);
    doc.text(`Submission ID: ${submission.id}`);
    doc.moveDown();

    doc.fontSize(12).text("Access URLs", { underline: true });
    doc.fontSize(10);
    doc.text(`BGOS: ${publicBgosOrigin()}`);
    doc.text(`ICECONNECT: ${publicIceconnectOrigin()}`);
    doc.text("Employees: use company invite / reset password from admin — passwords are never stored in this document.");
    doc.moveDown();

    doc.fontSize(12).text("Team emails (active members)", { underline: true });
    doc.fontSize(9);
    for (const m of members) {
      if (!m.user.isActive) continue;
      doc.text(`• ${m.user.name} <${m.user.email}>`);
    }
    doc.moveDown();

    doc.fontSize(12).text("User manuals", { underline: true });
    doc.fontSize(9);
    if (manuals.length === 0) doc.text("— None uploaded yet —");
    else for (const m of manuals) doc.text(`• ${m.category}: ${m.fileUrl}`);
    doc.moveDown();

    doc.fontSize(12).text("Onboarding responses", { underline: true });
    doc.fontSize(9);
    for (const sec of sections.sections) {
      doc.moveDown(0.3);
      doc.fontSize(10).text(sec.title, { underline: true });
      doc.fontSize(9);
      for (const f of sec.fields) {
        const val = typeof data[f.key] === "string" ? data[f.key].trim() : "";
        doc.text(`${f.label}: ${val || "—"}`);
      }
    }

    doc.moveDown();
    doc.fontSize(8).fillColor("#666").text("Generated by BGOS onboarding workflow.", { align: "center" });

    doc.end();
    stream.on("finish", () => resolve());
    stream.on("error", reject);
  });

  return publicPath;
}
