-- Rename old role values to the new solar CRM structure.
ALTER TYPE "UserRole" RENAME VALUE 'TELECALLER' TO 'SALES_EXECUTIVE';
ALTER TYPE "UserRole" RENAME VALUE 'ENGINEER' TO 'SITE_ENGINEER';
ALTER TYPE "UserRole" RENAME VALUE 'INSTALLER' TO 'INSTALLATION_TEAM';
ALTER TYPE "UserRole" RENAME VALUE 'ACCOUNTS' TO 'ACCOUNTANT';
ALTER TYPE "UserRole" RENAME VALUE 'SERVICE' TO 'SERVICE_TEAM';

-- Add newly introduced roles.
ALTER TYPE "UserRole" ADD VALUE 'SALES_HEAD';
ALTER TYPE "UserRole" ADD VALUE 'CHANNEL_PARTNER';
ALTER TYPE "UserRole" ADD VALUE 'OPERATIONS_HEAD';
ALTER TYPE "UserRole" ADD VALUE 'PRO';
ALTER TYPE "UserRole" ADD VALUE 'INVENTORY_MANAGER';
ALTER TYPE "UserRole" ADD VALUE 'LCO';
ALTER TYPE "UserRole" ADD VALUE 'HR_MANAGER';
